package classfile.code.opcodes;

public enum OpType {

	NOOP,
	CONSTANT_LOAD,
	LOCAL_LOAD, ARRAY_LOAD,
	LOCAL_STORE, ARRAY_STORE,
	STACK_MANAGE,
	ARITHMETIC, NEGATE, SHIFT,
	LOCAL_INCREMENT,
	CONVERT,
	COMPARE,
	CONDITIONAL_JUMP, COMPARE_JUMP,
	UNCONDITIONAL_JUMP,
	SUBROUTINE_JUMP, SUBROUTINE_RETURN,
	SWITCH,
	RETURN,
	FIELD_LOAD, FIELD_STORE,
	METHOD_INVOKE,
	NEW_OBJECT, NEW_ARRAY,
	ARRAY_LENGTH,
	THROW,
	CAST, INSTANCE_OF,
	SYNCHRONIZE,
	NULL_JUMP
}
